version = 1

[merge]
automerge_label = 'dependencies'
optimistic_updates = true
prioritize_ready_to_merge = true

[approve]
auto_approve_usernames = 'dependabot'

[update]
always = true
ignored_usernames = ["dependabot"]