steps:

  - commands: 
    - "bundle install"
    - "bundle exec rake db:drop"
    - "bundle exec rake db:create"
    - "RACK_ENV=test bundle exec rake db:migrate"
    - "bundle exec rspec"
    label: ":rspec:"
  
  - wait
  
  - commands: 
    - "yarn install"
    - "tsc -p client --declaration false"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - wait

  - commands: 
      - RACK_ENV=test bundle exec rake db:reset
      - "yarn install"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":parcel: :cypress:"
    artifact_paths:
      - public/*
      - cypress/videos/*