steps:

  - commands: 
    - "bundle install"
    - "bundle exec rspec"
    label: ":rspec:"
  
  - commands: 
    - "yarn install"
    - "yarn tsc -p client --declaration false"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn ci:lint"
    label: ":prettier: :plus: :eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - wait
  
  - commands: 
      - "bundle install" 
      - "yarn install"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":cypress:"
 
