steps:

  - commands: 
    - "bundle install"
    - "bundle exec rspec"
    label: ":rspec:"

  - commands: 
    - "yarn install"
    - "yarn tsc -p client --declaration false"
    label: ":typescript:"

  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - commands: 
      - "bundle install" 
      - "yarn install"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":cypress:"
 
