steps:

  - commands: 
    - "bundle install"
    - "bundle exec rspec"
    label: ":rspec:"
  
  - commands: 
    - "yarn install"
    - "yarn tsc -p client --declaration false"
    label: ":typescript:"
    artifact_paths:
      - "node_modules/**/*"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - wait
  
  - commands: 
      - "bundle install" 
      - "yarn install"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":cypress:"
 
