steps:

  - commands: 
    - "bundle update"
    - "bundle exec rspec"
    label: ":rspec:"
  
  - wait
  
  - commands: 
    - "yarn install"
    - "yarn tsc -p client --declaration false"
    label: ":typescript:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn lint"
    label: ":eslint:"

  - wait
  
  - commands: 
    - "yarn install"
    - "yarn test"
    label: ":jest:"

  - wait

  - commands: 
      - "yarn parcel --version"
      - "yarn install --force"
      - "yarn build"
      - "yarn cypress:ci"
    label: ":parcel: :cypress:"
    artifact_paths:
      - public/*
      - cypress/videos/*